name: Build

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches: [ main ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - uses: actions/checkout@v3
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test